namespace DA1
{
    partial class QuanLy
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(QuanLy));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.background = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.sidebar = new Bunifu.UI.WinForms.BunifuPanel();
            this.Ticket_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Time_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Movies_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Category_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Room_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Nav = new System.Windows.Forms.Panel();
            this.income_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Account_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Customer_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Staff_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Database_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.content = new Bunifu.UI.WinForms.BunifuPanel();
            this.HoaDon = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.background.SuspendLayout();
            this.sidebar.SuspendLayout();
            this.Nav.SuspendLayout();
            this.SuspendLayout();
            // 
            // background
            // 
            this.background.BackColor = System.Drawing.Color.Transparent;
            this.background.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("background.BackgroundImage")));
            this.background.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.background.BorderRadius = 1;
            this.background.Controls.Add(this.sidebar);
            this.background.Controls.Add(this.Nav);
            this.background.Controls.Add(this.content);
            this.background.Dock = System.Windows.Forms.DockStyle.Fill;
            this.background.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.background.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.background.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.background.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(54)))), ((int)(((byte)(64)))));
            this.background.Location = new System.Drawing.Point(0, 0);
            this.background.Name = "background";
            this.background.Quality = 10;
            this.background.Size = new System.Drawing.Size(1212, 813);
            this.background.TabIndex = 1;
            // 
            // sidebar
            // 
            this.sidebar.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.sidebar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sidebar.BackgroundImage")));
            this.sidebar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.sidebar.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.sidebar.BorderRadius = 3;
            this.sidebar.BorderThickness = 3;
            this.sidebar.Controls.Add(this.Ticket_btn);
            this.sidebar.Controls.Add(this.Time_btn);
            this.sidebar.Controls.Add(this.Movies_btn);
            this.sidebar.Controls.Add(this.Category_btn);
            this.sidebar.Controls.Add(this.Room_btn);
            this.sidebar.Dock = System.Windows.Forms.DockStyle.Left;
            this.sidebar.Location = new System.Drawing.Point(0, 98);
            this.sidebar.Name = "sidebar";
            this.sidebar.ShowBorders = false;
            this.sidebar.Size = new System.Drawing.Size(147, 715);
            this.sidebar.TabIndex = 1;
            // 
            // Ticket_btn
            // 
            this.Ticket_btn.AllowAnimations = true;
            this.Ticket_btn.AllowMouseEffects = true;
            this.Ticket_btn.AllowToggling = false;
            this.Ticket_btn.AnimationSpeed = 200;
            this.Ticket_btn.AutoGenerateColors = false;
            this.Ticket_btn.AutoRoundBorders = false;
            this.Ticket_btn.AutoSizeLeftIcon = true;
            this.Ticket_btn.AutoSizeRightIcon = true;
            this.Ticket_btn.BackColor = System.Drawing.Color.Transparent;
            this.Ticket_btn.BackColor1 = System.Drawing.Color.Transparent;
            this.Ticket_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Ticket_btn.BackgroundImage")));
            this.Ticket_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Ticket_btn.ButtonText = "Vé";
            this.Ticket_btn.ButtonTextMarginLeft = 0;
            this.Ticket_btn.ColorContrastOnClick = 45;
            this.Ticket_btn.ColorContrastOnHover = 45;
            this.Ticket_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Ticket_btn.CustomizableEdges = borderEdges1;
            this.Ticket_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Ticket_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Ticket_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Ticket_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Ticket_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.Ticket_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Ticket_btn.ForeColor = System.Drawing.Color.White;
            this.Ticket_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Ticket_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Ticket_btn.IconLeftPadding = new System.Windows.Forms.Padding(0, 3, 5, 3);
            this.Ticket_btn.IconMarginLeft = 11;
            this.Ticket_btn.IconPadding = 10;
            this.Ticket_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Ticket_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Ticket_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 10, 3);
            this.Ticket_btn.IconSize = 25;
            this.Ticket_btn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Ticket_btn.IdleBorderRadius = 1;
            this.Ticket_btn.IdleBorderThickness = 1;
            this.Ticket_btn.IdleFillColor = System.Drawing.Color.Transparent;
            this.Ticket_btn.IdleIconLeftImage = global::DA1.Properties.Resources.ticket_icon;
            this.Ticket_btn.IdleIconRightImage = null;
            this.Ticket_btn.IndicateFocus = false;
            this.Ticket_btn.Location = new System.Drawing.Point(3, 295);
            this.Ticket_btn.Name = "Ticket_btn";
            this.Ticket_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Ticket_btn.OnDisabledState.BorderRadius = 1;
            this.Ticket_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Ticket_btn.OnDisabledState.BorderThickness = 1;
            this.Ticket_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Ticket_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Ticket_btn.OnDisabledState.IconLeftImage = null;
            this.Ticket_btn.OnDisabledState.IconRightImage = null;
            this.Ticket_btn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.Ticket_btn.onHoverState.BorderRadius = 1;
            this.Ticket_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Ticket_btn.onHoverState.BorderThickness = 1;
            this.Ticket_btn.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.Ticket_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Ticket_btn.onHoverState.IconLeftImage = null;
            this.Ticket_btn.onHoverState.IconRightImage = null;
            this.Ticket_btn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Ticket_btn.OnIdleState.BorderRadius = 1;
            this.Ticket_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Ticket_btn.OnIdleState.BorderThickness = 1;
            this.Ticket_btn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.Ticket_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Ticket_btn.OnIdleState.IconLeftImage = global::DA1.Properties.Resources.ticket_icon;
            this.Ticket_btn.OnIdleState.IconRightImage = null;
            this.Ticket_btn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.Ticket_btn.OnPressedState.BorderRadius = 1;
            this.Ticket_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Ticket_btn.OnPressedState.BorderThickness = 1;
            this.Ticket_btn.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.Ticket_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Ticket_btn.OnPressedState.IconLeftImage = null;
            this.Ticket_btn.OnPressedState.IconRightImage = null;
            this.Ticket_btn.Size = new System.Drawing.Size(144, 49);
            this.Ticket_btn.TabIndex = 4;
            this.Ticket_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Ticket_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Ticket_btn.TextMarginLeft = 0;
            this.Ticket_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Ticket_btn.UseDefaultRadiusAndThickness = true;
            this.Ticket_btn.Click += new System.EventHandler(this.Ticket_btn_Click);
            // 
            // Time_btn
            // 
            this.Time_btn.AllowAnimations = true;
            this.Time_btn.AllowMouseEffects = true;
            this.Time_btn.AllowToggling = false;
            this.Time_btn.AnimationSpeed = 200;
            this.Time_btn.AutoGenerateColors = false;
            this.Time_btn.AutoRoundBorders = false;
            this.Time_btn.AutoSizeLeftIcon = true;
            this.Time_btn.AutoSizeRightIcon = true;
            this.Time_btn.BackColor = System.Drawing.Color.Transparent;
            this.Time_btn.BackColor1 = System.Drawing.Color.Transparent;
            this.Time_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Time_btn.BackgroundImage")));
            this.Time_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Time_btn.ButtonText = "Ca chiếu ";
            this.Time_btn.ButtonTextMarginLeft = 0;
            this.Time_btn.ColorContrastOnClick = 45;
            this.Time_btn.ColorContrastOnHover = 45;
            this.Time_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Time_btn.CustomizableEdges = borderEdges2;
            this.Time_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Time_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Time_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Time_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Time_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.Time_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Time_btn.ForeColor = System.Drawing.Color.White;
            this.Time_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Time_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Time_btn.IconLeftPadding = new System.Windows.Forms.Padding(0, 3, 5, 3);
            this.Time_btn.IconMarginLeft = 11;
            this.Time_btn.IconPadding = 10;
            this.Time_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Time_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Time_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 10, 3);
            this.Time_btn.IconSize = 25;
            this.Time_btn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Time_btn.IdleBorderRadius = 1;
            this.Time_btn.IdleBorderThickness = 1;
            this.Time_btn.IdleFillColor = System.Drawing.Color.Transparent;
            this.Time_btn.IdleIconLeftImage = global::DA1.Properties.Resources.calender_icon;
            this.Time_btn.IdleIconRightImage = null;
            this.Time_btn.IndicateFocus = false;
            this.Time_btn.Location = new System.Drawing.Point(3, 240);
            this.Time_btn.Name = "Time_btn";
            this.Time_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Time_btn.OnDisabledState.BorderRadius = 1;
            this.Time_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Time_btn.OnDisabledState.BorderThickness = 1;
            this.Time_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Time_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Time_btn.OnDisabledState.IconLeftImage = null;
            this.Time_btn.OnDisabledState.IconRightImage = null;
            this.Time_btn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.Time_btn.onHoverState.BorderRadius = 1;
            this.Time_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Time_btn.onHoverState.BorderThickness = 1;
            this.Time_btn.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.Time_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Time_btn.onHoverState.IconLeftImage = null;
            this.Time_btn.onHoverState.IconRightImage = null;
            this.Time_btn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Time_btn.OnIdleState.BorderRadius = 1;
            this.Time_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Time_btn.OnIdleState.BorderThickness = 1;
            this.Time_btn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.Time_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Time_btn.OnIdleState.IconLeftImage = global::DA1.Properties.Resources.calender_icon;
            this.Time_btn.OnIdleState.IconRightImage = null;
            this.Time_btn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.Time_btn.OnPressedState.BorderRadius = 1;
            this.Time_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Time_btn.OnPressedState.BorderThickness = 1;
            this.Time_btn.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.Time_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Time_btn.OnPressedState.IconLeftImage = null;
            this.Time_btn.OnPressedState.IconRightImage = null;
            this.Time_btn.Size = new System.Drawing.Size(144, 49);
            this.Time_btn.TabIndex = 3;
            this.Time_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Time_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Time_btn.TextMarginLeft = 0;
            this.Time_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Time_btn.UseDefaultRadiusAndThickness = true;
            this.Time_btn.Click += new System.EventHandler(this.Time_btn_Click);
            // 
            // Movies_btn
            // 
            this.Movies_btn.AllowAnimations = true;
            this.Movies_btn.AllowMouseEffects = true;
            this.Movies_btn.AllowToggling = false;
            this.Movies_btn.AnimationSpeed = 200;
            this.Movies_btn.AutoGenerateColors = false;
            this.Movies_btn.AutoRoundBorders = false;
            this.Movies_btn.AutoSizeLeftIcon = true;
            this.Movies_btn.AutoSizeRightIcon = true;
            this.Movies_btn.BackColor = System.Drawing.Color.Transparent;
            this.Movies_btn.BackColor1 = System.Drawing.Color.Transparent;
            this.Movies_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Movies_btn.BackgroundImage")));
            this.Movies_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Movies_btn.ButtonText = "Phim";
            this.Movies_btn.ButtonTextMarginLeft = 0;
            this.Movies_btn.ColorContrastOnClick = 45;
            this.Movies_btn.ColorContrastOnHover = 45;
            this.Movies_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Movies_btn.CustomizableEdges = borderEdges3;
            this.Movies_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Movies_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Movies_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Movies_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Movies_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.Movies_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Movies_btn.ForeColor = System.Drawing.Color.White;
            this.Movies_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Movies_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Movies_btn.IconLeftPadding = new System.Windows.Forms.Padding(0, 3, 5, 3);
            this.Movies_btn.IconMarginLeft = 11;
            this.Movies_btn.IconPadding = 10;
            this.Movies_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Movies_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Movies_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 10, 3);
            this.Movies_btn.IconSize = 25;
            this.Movies_btn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Movies_btn.IdleBorderRadius = 1;
            this.Movies_btn.IdleBorderThickness = 1;
            this.Movies_btn.IdleFillColor = System.Drawing.Color.Transparent;
            this.Movies_btn.IdleIconLeftImage = global::DA1.Properties.Resources.room;
            this.Movies_btn.IdleIconRightImage = null;
            this.Movies_btn.IndicateFocus = false;
            this.Movies_btn.Location = new System.Drawing.Point(3, 185);
            this.Movies_btn.Name = "Movies_btn";
            this.Movies_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Movies_btn.OnDisabledState.BorderRadius = 1;
            this.Movies_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Movies_btn.OnDisabledState.BorderThickness = 1;
            this.Movies_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Movies_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Movies_btn.OnDisabledState.IconLeftImage = null;
            this.Movies_btn.OnDisabledState.IconRightImage = null;
            this.Movies_btn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.Movies_btn.onHoverState.BorderRadius = 1;
            this.Movies_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Movies_btn.onHoverState.BorderThickness = 1;
            this.Movies_btn.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.Movies_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Movies_btn.onHoverState.IconLeftImage = null;
            this.Movies_btn.onHoverState.IconRightImage = null;
            this.Movies_btn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Movies_btn.OnIdleState.BorderRadius = 1;
            this.Movies_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Movies_btn.OnIdleState.BorderThickness = 1;
            this.Movies_btn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.Movies_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Movies_btn.OnIdleState.IconLeftImage = global::DA1.Properties.Resources.room;
            this.Movies_btn.OnIdleState.IconRightImage = null;
            this.Movies_btn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.Movies_btn.OnPressedState.BorderRadius = 1;
            this.Movies_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Movies_btn.OnPressedState.BorderThickness = 1;
            this.Movies_btn.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.Movies_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Movies_btn.OnPressedState.IconLeftImage = null;
            this.Movies_btn.OnPressedState.IconRightImage = null;
            this.Movies_btn.Size = new System.Drawing.Size(144, 49);
            this.Movies_btn.TabIndex = 2;
            this.Movies_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Movies_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Movies_btn.TextMarginLeft = 0;
            this.Movies_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Movies_btn.UseDefaultRadiusAndThickness = true;
            this.Movies_btn.Click += new System.EventHandler(this.Movies_btn_Click);
            // 
            // Category_btn
            // 
            this.Category_btn.AllowAnimations = true;
            this.Category_btn.AllowMouseEffects = true;
            this.Category_btn.AllowToggling = false;
            this.Category_btn.AnimationSpeed = 200;
            this.Category_btn.AutoGenerateColors = false;
            this.Category_btn.AutoRoundBorders = false;
            this.Category_btn.AutoSizeLeftIcon = true;
            this.Category_btn.AutoSizeRightIcon = true;
            this.Category_btn.BackColor = System.Drawing.Color.Transparent;
            this.Category_btn.BackColor1 = System.Drawing.Color.Transparent;
            this.Category_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Category_btn.BackgroundImage")));
            this.Category_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Category_btn.ButtonText = "Thể Loại";
            this.Category_btn.ButtonTextMarginLeft = 0;
            this.Category_btn.ColorContrastOnClick = 45;
            this.Category_btn.ColorContrastOnHover = 45;
            this.Category_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Category_btn.CustomizableEdges = borderEdges4;
            this.Category_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Category_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Category_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Category_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Category_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.Category_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Category_btn.ForeColor = System.Drawing.Color.White;
            this.Category_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Category_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Category_btn.IconLeftPadding = new System.Windows.Forms.Padding(0, 3, 5, 3);
            this.Category_btn.IconMarginLeft = 11;
            this.Category_btn.IconPadding = 10;
            this.Category_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Category_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Category_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 10, 3);
            this.Category_btn.IconSize = 25;
            this.Category_btn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Category_btn.IdleBorderRadius = 1;
            this.Category_btn.IdleBorderThickness = 1;
            this.Category_btn.IdleFillColor = System.Drawing.Color.Transparent;
            this.Category_btn.IdleIconLeftImage = global::DA1.Properties.Resources.room;
            this.Category_btn.IdleIconRightImage = null;
            this.Category_btn.IndicateFocus = false;
            this.Category_btn.Location = new System.Drawing.Point(3, 130);
            this.Category_btn.Name = "Category_btn";
            this.Category_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Category_btn.OnDisabledState.BorderRadius = 1;
            this.Category_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Category_btn.OnDisabledState.BorderThickness = 1;
            this.Category_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Category_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Category_btn.OnDisabledState.IconLeftImage = null;
            this.Category_btn.OnDisabledState.IconRightImage = null;
            this.Category_btn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.Category_btn.onHoverState.BorderRadius = 1;
            this.Category_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Category_btn.onHoverState.BorderThickness = 1;
            this.Category_btn.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.Category_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Category_btn.onHoverState.IconLeftImage = null;
            this.Category_btn.onHoverState.IconRightImage = null;
            this.Category_btn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Category_btn.OnIdleState.BorderRadius = 1;
            this.Category_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Category_btn.OnIdleState.BorderThickness = 1;
            this.Category_btn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.Category_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Category_btn.OnIdleState.IconLeftImage = global::DA1.Properties.Resources.room;
            this.Category_btn.OnIdleState.IconRightImage = null;
            this.Category_btn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.Category_btn.OnPressedState.BorderRadius = 1;
            this.Category_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Category_btn.OnPressedState.BorderThickness = 1;
            this.Category_btn.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.Category_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Category_btn.OnPressedState.IconLeftImage = null;
            this.Category_btn.OnPressedState.IconRightImage = null;
            this.Category_btn.Size = new System.Drawing.Size(144, 49);
            this.Category_btn.TabIndex = 1;
            this.Category_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Category_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Category_btn.TextMarginLeft = 0;
            this.Category_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Category_btn.UseDefaultRadiusAndThickness = true;
            this.Category_btn.Click += new System.EventHandler(this.Category_btn_Click);
            // 
            // Room_btn
            // 
            this.Room_btn.AllowAnimations = true;
            this.Room_btn.AllowMouseEffects = true;
            this.Room_btn.AllowToggling = false;
            this.Room_btn.AnimationSpeed = 200;
            this.Room_btn.AutoGenerateColors = false;
            this.Room_btn.AutoRoundBorders = false;
            this.Room_btn.AutoSizeLeftIcon = true;
            this.Room_btn.AutoSizeRightIcon = true;
            this.Room_btn.BackColor = System.Drawing.Color.Transparent;
            this.Room_btn.BackColor1 = System.Drawing.Color.Transparent;
            this.Room_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Room_btn.BackgroundImage")));
            this.Room_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Room_btn.ButtonText = "Phòng Chiếu ";
            this.Room_btn.ButtonTextMarginLeft = 0;
            this.Room_btn.ColorContrastOnClick = 45;
            this.Room_btn.ColorContrastOnHover = 45;
            this.Room_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.Room_btn.CustomizableEdges = borderEdges5;
            this.Room_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Room_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Room_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Room_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Room_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.Room_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Room_btn.ForeColor = System.Drawing.Color.White;
            this.Room_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Room_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Room_btn.IconLeftPadding = new System.Windows.Forms.Padding(0, 3, 5, 3);
            this.Room_btn.IconMarginLeft = 11;
            this.Room_btn.IconPadding = 10;
            this.Room_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Room_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Room_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 10, 3);
            this.Room_btn.IconSize = 25;
            this.Room_btn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Room_btn.IdleBorderRadius = 1;
            this.Room_btn.IdleBorderThickness = 1;
            this.Room_btn.IdleFillColor = System.Drawing.Color.Transparent;
            this.Room_btn.IdleIconLeftImage = global::DA1.Properties.Resources.room;
            this.Room_btn.IdleIconRightImage = null;
            this.Room_btn.IndicateFocus = false;
            this.Room_btn.Location = new System.Drawing.Point(3, 75);
            this.Room_btn.Name = "Room_btn";
            this.Room_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Room_btn.OnDisabledState.BorderRadius = 1;
            this.Room_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Room_btn.OnDisabledState.BorderThickness = 1;
            this.Room_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Room_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Room_btn.OnDisabledState.IconLeftImage = null;
            this.Room_btn.OnDisabledState.IconRightImage = null;
            this.Room_btn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.Room_btn.onHoverState.BorderRadius = 1;
            this.Room_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Room_btn.onHoverState.BorderThickness = 1;
            this.Room_btn.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.Room_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Room_btn.onHoverState.IconLeftImage = null;
            this.Room_btn.onHoverState.IconRightImage = null;
            this.Room_btn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Room_btn.OnIdleState.BorderRadius = 1;
            this.Room_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Room_btn.OnIdleState.BorderThickness = 1;
            this.Room_btn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.Room_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Room_btn.OnIdleState.IconLeftImage = global::DA1.Properties.Resources.room;
            this.Room_btn.OnIdleState.IconRightImage = null;
            this.Room_btn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.Room_btn.OnPressedState.BorderRadius = 1;
            this.Room_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Room_btn.OnPressedState.BorderThickness = 1;
            this.Room_btn.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.Room_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Room_btn.OnPressedState.IconLeftImage = null;
            this.Room_btn.OnPressedState.IconRightImage = null;
            this.Room_btn.Size = new System.Drawing.Size(144, 49);
            this.Room_btn.TabIndex = 0;
            this.Room_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Room_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Room_btn.TextMarginLeft = 0;
            this.Room_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Room_btn.UseDefaultRadiusAndThickness = true;
            this.Room_btn.Click += new System.EventHandler(this.Room_btn_Click);
            // 
            // Nav
            // 
            this.Nav.BackColor = System.Drawing.Color.Black;
            this.Nav.Controls.Add(this.HoaDon);
            this.Nav.Controls.Add(this.income_btn);
            this.Nav.Controls.Add(this.Account_btn);
            this.Nav.Controls.Add(this.Customer_btn);
            this.Nav.Controls.Add(this.Staff_btn);
            this.Nav.Controls.Add(this.Database_btn);
            this.Nav.Dock = System.Windows.Forms.DockStyle.Top;
            this.Nav.Location = new System.Drawing.Point(0, 0);
            this.Nav.Name = "Nav";
            this.Nav.Size = new System.Drawing.Size(1212, 98);
            this.Nav.TabIndex = 1;
            // 
            // income_btn
            // 
            this.income_btn.AllowAnimations = true;
            this.income_btn.AllowMouseEffects = true;
            this.income_btn.AllowToggling = false;
            this.income_btn.AnimationSpeed = 200;
            this.income_btn.AutoGenerateColors = false;
            this.income_btn.AutoRoundBorders = false;
            this.income_btn.AutoSizeLeftIcon = true;
            this.income_btn.AutoSizeRightIcon = true;
            this.income_btn.BackColor = System.Drawing.Color.Transparent;
            this.income_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(204)))), ((int)(((byte)(26)))));
            this.income_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("income_btn.BackgroundImage")));
            this.income_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.income_btn.ButtonText = "Doanh thu";
            this.income_btn.ButtonTextMarginLeft = 0;
            this.income_btn.ColorContrastOnClick = 45;
            this.income_btn.ColorContrastOnHover = 45;
            this.income_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.income_btn.CustomizableEdges = borderEdges7;
            this.income_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.income_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.income_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.income_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.income_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.income_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.income_btn.ForeColor = System.Drawing.Color.Transparent;
            this.income_btn.IconLeftAlign = System.Drawing.ContentAlignment.TopLeft;
            this.income_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.income_btn.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.income_btn.IconMarginLeft = 11;
            this.income_btn.IconPadding = 10;
            this.income_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.income_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.income_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.income_btn.IconSize = 25;
            this.income_btn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.income_btn.IdleBorderRadius = 1;
            this.income_btn.IdleBorderThickness = 1;
            this.income_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(204)))), ((int)(((byte)(26)))));
            this.income_btn.IdleIconLeftImage = global::DA1.Properties.Resources.income_icon;
            this.income_btn.IdleIconRightImage = null;
            this.income_btn.IndicateFocus = false;
            this.income_btn.Location = new System.Drawing.Point(649, 12);
            this.income_btn.Name = "income_btn";
            this.income_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.income_btn.OnDisabledState.BorderRadius = 1;
            this.income_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.income_btn.OnDisabledState.BorderThickness = 1;
            this.income_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.income_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.income_btn.OnDisabledState.IconLeftImage = null;
            this.income_btn.OnDisabledState.IconRightImage = null;
            this.income_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.income_btn.onHoverState.BorderRadius = 1;
            this.income_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.income_btn.onHoverState.BorderThickness = 1;
            this.income_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(204)))), ((int)(((byte)(26)))));
            this.income_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.income_btn.onHoverState.IconLeftImage = null;
            this.income_btn.onHoverState.IconRightImage = null;
            this.income_btn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.income_btn.OnIdleState.BorderRadius = 1;
            this.income_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.income_btn.OnIdleState.BorderThickness = 1;
            this.income_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(204)))), ((int)(((byte)(26)))));
            this.income_btn.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.income_btn.OnIdleState.IconLeftImage = global::DA1.Properties.Resources.income_icon;
            this.income_btn.OnIdleState.IconRightImage = null;
            this.income_btn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.income_btn.OnPressedState.BorderRadius = 1;
            this.income_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.income_btn.OnPressedState.BorderThickness = 1;
            this.income_btn.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.income_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.income_btn.OnPressedState.IconLeftImage = null;
            this.income_btn.OnPressedState.IconRightImage = null;
            this.income_btn.Size = new System.Drawing.Size(135, 69);
            this.income_btn.TabIndex = 5;
            this.income_btn.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.income_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.income_btn.TextMarginLeft = 0;
            this.income_btn.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.income_btn.UseDefaultRadiusAndThickness = true;
            this.income_btn.Click += new System.EventHandler(this.income_btn_Click);
            // 
            // Account_btn
            // 
            this.Account_btn.AllowAnimations = true;
            this.Account_btn.AllowMouseEffects = true;
            this.Account_btn.AllowToggling = false;
            this.Account_btn.AnimationSpeed = 200;
            this.Account_btn.AutoGenerateColors = false;
            this.Account_btn.AutoRoundBorders = false;
            this.Account_btn.AutoSizeLeftIcon = true;
            this.Account_btn.AutoSizeRightIcon = true;
            this.Account_btn.BackColor = System.Drawing.Color.Transparent;
            this.Account_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(113)))), ((int)(((byte)(178)))));
            this.Account_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Account_btn.BackgroundImage")));
            this.Account_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Account_btn.ButtonText = "Tài khoản ";
            this.Account_btn.ButtonTextMarginLeft = 0;
            this.Account_btn.ColorContrastOnClick = 45;
            this.Account_btn.ColorContrastOnHover = 45;
            this.Account_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.Account_btn.CustomizableEdges = borderEdges8;
            this.Account_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Account_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Account_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Account_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Account_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.Account_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Account_btn.ForeColor = System.Drawing.Color.Transparent;
            this.Account_btn.IconLeftAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Account_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Account_btn.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.Account_btn.IconMarginLeft = 11;
            this.Account_btn.IconPadding = 10;
            this.Account_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Account_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Account_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Account_btn.IconSize = 25;
            this.Account_btn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Account_btn.IdleBorderRadius = 1;
            this.Account_btn.IdleBorderThickness = 1;
            this.Account_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(113)))), ((int)(((byte)(178)))));
            this.Account_btn.IdleIconLeftImage = global::DA1.Properties.Resources.accont_icon;
            this.Account_btn.IdleIconRightImage = null;
            this.Account_btn.IndicateFocus = false;
            this.Account_btn.Location = new System.Drawing.Point(488, 12);
            this.Account_btn.Name = "Account_btn";
            this.Account_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Account_btn.OnDisabledState.BorderRadius = 1;
            this.Account_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Account_btn.OnDisabledState.BorderThickness = 1;
            this.Account_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Account_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Account_btn.OnDisabledState.IconLeftImage = null;
            this.Account_btn.OnDisabledState.IconRightImage = null;
            this.Account_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Account_btn.onHoverState.BorderRadius = 1;
            this.Account_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Account_btn.onHoverState.BorderThickness = 1;
            this.Account_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(113)))), ((int)(((byte)(178)))));
            this.Account_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Account_btn.onHoverState.IconLeftImage = null;
            this.Account_btn.onHoverState.IconRightImage = null;
            this.Account_btn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Account_btn.OnIdleState.BorderRadius = 1;
            this.Account_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Account_btn.OnIdleState.BorderThickness = 1;
            this.Account_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(113)))), ((int)(((byte)(178)))));
            this.Account_btn.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.Account_btn.OnIdleState.IconLeftImage = global::DA1.Properties.Resources.accont_icon;
            this.Account_btn.OnIdleState.IconRightImage = null;
            this.Account_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Account_btn.OnPressedState.BorderRadius = 1;
            this.Account_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Account_btn.OnPressedState.BorderThickness = 1;
            this.Account_btn.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.Account_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Account_btn.OnPressedState.IconLeftImage = null;
            this.Account_btn.OnPressedState.IconRightImage = null;
            this.Account_btn.Size = new System.Drawing.Size(135, 69);
            this.Account_btn.TabIndex = 4;
            this.Account_btn.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.Account_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Account_btn.TextMarginLeft = 0;
            this.Account_btn.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.Account_btn.UseDefaultRadiusAndThickness = true;
            this.Account_btn.Click += new System.EventHandler(this.Account_btn_Click);
            // 
            // Customer_btn
            // 
            this.Customer_btn.AllowAnimations = true;
            this.Customer_btn.AllowMouseEffects = true;
            this.Customer_btn.AllowToggling = false;
            this.Customer_btn.AnimationSpeed = 200;
            this.Customer_btn.AutoGenerateColors = false;
            this.Customer_btn.AutoRoundBorders = false;
            this.Customer_btn.AutoSizeLeftIcon = true;
            this.Customer_btn.AutoSizeRightIcon = true;
            this.Customer_btn.BackColor = System.Drawing.Color.Transparent;
            this.Customer_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(35)))), ((int)(((byte)(34)))));
            this.Customer_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Customer_btn.BackgroundImage")));
            this.Customer_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Customer_btn.ButtonText = "Khách hàng ";
            this.Customer_btn.ButtonTextMarginLeft = 0;
            this.Customer_btn.ColorContrastOnClick = 45;
            this.Customer_btn.ColorContrastOnHover = 45;
            this.Customer_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.Customer_btn.CustomizableEdges = borderEdges9;
            this.Customer_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Customer_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Customer_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Customer_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Customer_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.Customer_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Customer_btn.ForeColor = System.Drawing.Color.Transparent;
            this.Customer_btn.IconLeftAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Customer_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Customer_btn.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.Customer_btn.IconMarginLeft = 11;
            this.Customer_btn.IconPadding = 10;
            this.Customer_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Customer_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Customer_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Customer_btn.IconSize = 25;
            this.Customer_btn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Customer_btn.IdleBorderRadius = 1;
            this.Customer_btn.IdleBorderThickness = 1;
            this.Customer_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(35)))), ((int)(((byte)(34)))));
            this.Customer_btn.IdleIconLeftImage = global::DA1.Properties.Resources.people_icon;
            this.Customer_btn.IdleIconRightImage = null;
            this.Customer_btn.IndicateFocus = false;
            this.Customer_btn.Location = new System.Drawing.Point(330, 12);
            this.Customer_btn.Name = "Customer_btn";
            this.Customer_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Customer_btn.OnDisabledState.BorderRadius = 1;
            this.Customer_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Customer_btn.OnDisabledState.BorderThickness = 1;
            this.Customer_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Customer_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Customer_btn.OnDisabledState.IconLeftImage = null;
            this.Customer_btn.OnDisabledState.IconRightImage = null;
            this.Customer_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Customer_btn.onHoverState.BorderRadius = 1;
            this.Customer_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Customer_btn.onHoverState.BorderThickness = 1;
            this.Customer_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(35)))), ((int)(((byte)(34)))));
            this.Customer_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Customer_btn.onHoverState.IconLeftImage = null;
            this.Customer_btn.onHoverState.IconRightImage = null;
            this.Customer_btn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Customer_btn.OnIdleState.BorderRadius = 1;
            this.Customer_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Customer_btn.OnIdleState.BorderThickness = 1;
            this.Customer_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(35)))), ((int)(((byte)(34)))));
            this.Customer_btn.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.Customer_btn.OnIdleState.IconLeftImage = global::DA1.Properties.Resources.people_icon;
            this.Customer_btn.OnIdleState.IconRightImage = null;
            this.Customer_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Customer_btn.OnPressedState.BorderRadius = 1;
            this.Customer_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Customer_btn.OnPressedState.BorderThickness = 1;
            this.Customer_btn.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.Customer_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Customer_btn.OnPressedState.IconLeftImage = null;
            this.Customer_btn.OnPressedState.IconRightImage = null;
            this.Customer_btn.Size = new System.Drawing.Size(135, 69);
            this.Customer_btn.TabIndex = 3;
            this.Customer_btn.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.Customer_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Customer_btn.TextMarginLeft = 0;
            this.Customer_btn.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.Customer_btn.UseDefaultRadiusAndThickness = true;
            this.Customer_btn.Click += new System.EventHandler(this.Customer_btn_Click);
            // 
            // Staff_btn
            // 
            this.Staff_btn.AllowAnimations = true;
            this.Staff_btn.AllowMouseEffects = true;
            this.Staff_btn.AllowToggling = false;
            this.Staff_btn.AnimationSpeed = 200;
            this.Staff_btn.AutoGenerateColors = false;
            this.Staff_btn.AutoRoundBorders = false;
            this.Staff_btn.AutoSizeLeftIcon = true;
            this.Staff_btn.AutoSizeRightIcon = true;
            this.Staff_btn.BackColor = System.Drawing.Color.Transparent;
            this.Staff_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(144)))), ((int)(((byte)(1)))));
            this.Staff_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Staff_btn.BackgroundImage")));
            this.Staff_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Staff_btn.ButtonText = "Nhân viên ";
            this.Staff_btn.ButtonTextMarginLeft = 0;
            this.Staff_btn.ColorContrastOnClick = 45;
            this.Staff_btn.ColorContrastOnHover = 45;
            this.Staff_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.Staff_btn.CustomizableEdges = borderEdges10;
            this.Staff_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Staff_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Staff_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Staff_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Staff_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.Staff_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Staff_btn.ForeColor = System.Drawing.Color.Transparent;
            this.Staff_btn.IconLeftAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Staff_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Staff_btn.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.Staff_btn.IconMarginLeft = 11;
            this.Staff_btn.IconPadding = 10;
            this.Staff_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Staff_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Staff_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Staff_btn.IconSize = 25;
            this.Staff_btn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Staff_btn.IdleBorderRadius = 1;
            this.Staff_btn.IdleBorderThickness = 1;
            this.Staff_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(144)))), ((int)(((byte)(1)))));
            this.Staff_btn.IdleIconLeftImage = global::DA1.Properties.Resources.human_icon;
            this.Staff_btn.IdleIconRightImage = null;
            this.Staff_btn.IndicateFocus = false;
            this.Staff_btn.Location = new System.Drawing.Point(171, 12);
            this.Staff_btn.Name = "Staff_btn";
            this.Staff_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Staff_btn.OnDisabledState.BorderRadius = 1;
            this.Staff_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Staff_btn.OnDisabledState.BorderThickness = 1;
            this.Staff_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Staff_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Staff_btn.OnDisabledState.IconLeftImage = null;
            this.Staff_btn.OnDisabledState.IconRightImage = null;
            this.Staff_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Staff_btn.onHoverState.BorderRadius = 1;
            this.Staff_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Staff_btn.onHoverState.BorderThickness = 1;
            this.Staff_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(144)))), ((int)(((byte)(1)))));
            this.Staff_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Staff_btn.onHoverState.IconLeftImage = null;
            this.Staff_btn.onHoverState.IconRightImage = null;
            this.Staff_btn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Staff_btn.OnIdleState.BorderRadius = 1;
            this.Staff_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Staff_btn.OnIdleState.BorderThickness = 1;
            this.Staff_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(144)))), ((int)(((byte)(1)))));
            this.Staff_btn.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.Staff_btn.OnIdleState.IconLeftImage = global::DA1.Properties.Resources.human_icon;
            this.Staff_btn.OnIdleState.IconRightImage = null;
            this.Staff_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Staff_btn.OnPressedState.BorderRadius = 1;
            this.Staff_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Staff_btn.OnPressedState.BorderThickness = 1;
            this.Staff_btn.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.Staff_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Staff_btn.OnPressedState.IconLeftImage = null;
            this.Staff_btn.OnPressedState.IconRightImage = null;
            this.Staff_btn.Size = new System.Drawing.Size(135, 69);
            this.Staff_btn.TabIndex = 2;
            this.Staff_btn.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.Staff_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Staff_btn.TextMarginLeft = 0;
            this.Staff_btn.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.Staff_btn.UseDefaultRadiusAndThickness = true;
            this.Staff_btn.Click += new System.EventHandler(this.Staff_btn_Click);
            // 
            // Database_btn
            // 
            this.Database_btn.AllowAnimations = false;
            this.Database_btn.AllowMouseEffects = true;
            this.Database_btn.AllowToggling = false;
            this.Database_btn.AnimationSpeed = 200;
            this.Database_btn.AutoGenerateColors = false;
            this.Database_btn.AutoRoundBorders = false;
            this.Database_btn.AutoSizeLeftIcon = true;
            this.Database_btn.AutoSizeRightIcon = true;
            this.Database_btn.BackColor = System.Drawing.Color.Transparent;
            this.Database_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(143)))), ((int)(((byte)(90)))));
            this.Database_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Database_btn.BackgroundImage")));
            this.Database_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Database_btn.ButtonText = "Dữ liệu ";
            this.Database_btn.ButtonTextMarginLeft = 0;
            this.Database_btn.ColorContrastOnClick = 45;
            this.Database_btn.ColorContrastOnHover = 45;
            this.Database_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.Database_btn.CustomizableEdges = borderEdges11;
            this.Database_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Database_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Database_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Database_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Database_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.Database_btn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Database_btn.ForeColor = System.Drawing.Color.Transparent;
            this.Database_btn.IconLeftAlign = System.Drawing.ContentAlignment.TopLeft;
            this.Database_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Database_btn.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.Database_btn.IconMarginLeft = 11;
            this.Database_btn.IconPadding = 10;
            this.Database_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Database_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Database_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Database_btn.IconSize = 25;
            this.Database_btn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Database_btn.IdleBorderRadius = 1;
            this.Database_btn.IdleBorderThickness = 1;
            this.Database_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(143)))), ((int)(((byte)(90)))));
            this.Database_btn.IdleIconLeftImage = global::DA1.Properties.Resources.folder_icon;
            this.Database_btn.IdleIconRightImage = null;
            this.Database_btn.IndicateFocus = false;
            this.Database_btn.Location = new System.Drawing.Point(12, 12);
            this.Database_btn.Name = "Database_btn";
            this.Database_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Database_btn.OnDisabledState.BorderRadius = 1;
            this.Database_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Database_btn.OnDisabledState.BorderThickness = 1;
            this.Database_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Database_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Database_btn.OnDisabledState.IconLeftImage = null;
            this.Database_btn.OnDisabledState.IconRightImage = null;
            this.Database_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Database_btn.onHoverState.BorderRadius = 1;
            this.Database_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Database_btn.onHoverState.BorderThickness = 1;
            this.Database_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(143)))), ((int)(((byte)(90)))));
            this.Database_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Database_btn.onHoverState.IconLeftImage = null;
            this.Database_btn.onHoverState.IconRightImage = null;
            this.Database_btn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Database_btn.OnIdleState.BorderRadius = 1;
            this.Database_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Database_btn.OnIdleState.BorderThickness = 1;
            this.Database_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(143)))), ((int)(((byte)(90)))));
            this.Database_btn.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.Database_btn.OnIdleState.IconLeftImage = global::DA1.Properties.Resources.folder_icon;
            this.Database_btn.OnIdleState.IconRightImage = null;
            this.Database_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Database_btn.OnPressedState.BorderRadius = 1;
            this.Database_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Database_btn.OnPressedState.BorderThickness = 1;
            this.Database_btn.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.Database_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Database_btn.OnPressedState.IconLeftImage = null;
            this.Database_btn.OnPressedState.IconRightImage = null;
            this.Database_btn.Size = new System.Drawing.Size(135, 69);
            this.Database_btn.TabIndex = 1;
            this.Database_btn.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.Database_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Database_btn.TextMarginLeft = 0;
            this.Database_btn.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.Database_btn.UseDefaultRadiusAndThickness = true;
            this.Database_btn.Click += new System.EventHandler(this.Database_btn_Click);
            // 
            // content
            // 
            this.content.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.content.BackgroundColor = System.Drawing.Color.LightGray;
            this.content.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("content.BackgroundImage")));
            this.content.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.content.BorderColor = System.Drawing.Color.Transparent;
            this.content.BorderRadius = 3;
            this.content.BorderThickness = 1;
            this.content.Location = new System.Drawing.Point(153, 104);
            this.content.Name = "content";
            this.content.ShowBorders = true;
            this.content.Size = new System.Drawing.Size(1047, 697);
            this.content.TabIndex = 2;
            // 
            // HoaDon
            // 
            this.HoaDon.AllowAnimations = true;
            this.HoaDon.AllowMouseEffects = true;
            this.HoaDon.AllowToggling = false;
            this.HoaDon.AnimationSpeed = 200;
            this.HoaDon.AutoGenerateColors = false;
            this.HoaDon.AutoRoundBorders = false;
            this.HoaDon.AutoSizeLeftIcon = true;
            this.HoaDon.AutoSizeRightIcon = true;
            this.HoaDon.BackColor = System.Drawing.Color.Transparent;
            this.HoaDon.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(140)))), ((int)(((byte)(141)))));
            this.HoaDon.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("HoaDon.BackgroundImage")));
            this.HoaDon.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HoaDon.ButtonText = "Hóa đơn";
            this.HoaDon.ButtonTextMarginLeft = 0;
            this.HoaDon.ColorContrastOnClick = 45;
            this.HoaDon.ColorContrastOnHover = 45;
            this.HoaDon.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.HoaDon.CustomizableEdges = borderEdges6;
            this.HoaDon.DialogResult = System.Windows.Forms.DialogResult.None;
            this.HoaDon.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.HoaDon.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.HoaDon.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.HoaDon.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.HoaDon.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.HoaDon.ForeColor = System.Drawing.Color.Transparent;
            this.HoaDon.IconLeftAlign = System.Drawing.ContentAlignment.TopLeft;
            this.HoaDon.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.HoaDon.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.HoaDon.IconMarginLeft = 11;
            this.HoaDon.IconPadding = 10;
            this.HoaDon.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.HoaDon.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.HoaDon.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.HoaDon.IconSize = 25;
            this.HoaDon.IdleBorderColor = System.Drawing.Color.Transparent;
            this.HoaDon.IdleBorderRadius = 1;
            this.HoaDon.IdleBorderThickness = 1;
            this.HoaDon.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(140)))), ((int)(((byte)(141)))));
            this.HoaDon.IdleIconLeftImage = global::DA1.Properties.Resources.income_icon;
            this.HoaDon.IdleIconRightImage = null;
            this.HoaDon.IndicateFocus = false;
            this.HoaDon.Location = new System.Drawing.Point(807, 12);
            this.HoaDon.Name = "HoaDon";
            this.HoaDon.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.HoaDon.OnDisabledState.BorderRadius = 1;
            this.HoaDon.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HoaDon.OnDisabledState.BorderThickness = 1;
            this.HoaDon.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.HoaDon.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.HoaDon.OnDisabledState.IconLeftImage = null;
            this.HoaDon.OnDisabledState.IconRightImage = null;
            this.HoaDon.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.HoaDon.onHoverState.BorderRadius = 1;
            this.HoaDon.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HoaDon.onHoverState.BorderThickness = 1;
            this.HoaDon.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(140)))), ((int)(((byte)(141)))));
            this.HoaDon.onHoverState.ForeColor = System.Drawing.Color.White;
            this.HoaDon.onHoverState.IconLeftImage = null;
            this.HoaDon.onHoverState.IconRightImage = null;
            this.HoaDon.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.HoaDon.OnIdleState.BorderRadius = 1;
            this.HoaDon.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HoaDon.OnIdleState.BorderThickness = 1;
            this.HoaDon.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(140)))), ((int)(((byte)(141)))));
            this.HoaDon.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.HoaDon.OnIdleState.IconLeftImage = global::DA1.Properties.Resources.income_icon;
            this.HoaDon.OnIdleState.IconRightImage = null;
            this.HoaDon.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.HoaDon.OnPressedState.BorderRadius = 1;
            this.HoaDon.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HoaDon.OnPressedState.BorderThickness = 1;
            this.HoaDon.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.HoaDon.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.HoaDon.OnPressedState.IconLeftImage = null;
            this.HoaDon.OnPressedState.IconRightImage = null;
            this.HoaDon.Size = new System.Drawing.Size(135, 69);
            this.HoaDon.TabIndex = 6;
            this.HoaDon.TextAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.HoaDon.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.HoaDon.TextMarginLeft = 0;
            this.HoaDon.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.HoaDon.UseDefaultRadiusAndThickness = true;
            this.HoaDon.Click += new System.EventHandler(this.HoaDon_Click);
            // 
            // QuanLy
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1212, 813);
            this.Controls.Add(this.background);
            this.Name = "QuanLy";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Management ";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.Management_Load);
            this.background.ResumeLayout(false);
            this.sidebar.ResumeLayout(false);
            this.Nav.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPanel sidebar;
        private Bunifu.UI.WinForms.BunifuGradientPanel background;
        private System.Windows.Forms.Panel Nav;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Database_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Staff_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Customer_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Account_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton income_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Room_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Category_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Movies_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Time_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Ticket_btn;
        private Bunifu.UI.WinForms.BunifuPanel content;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton HoaDon;
    }
}